### ISSUE TITLE
bash: graph: command not found

### ISSUE THREAD

**Issue by vishal590** [graphprotocol/graph-cli#1026]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

I installed graph-cli with following command
```npm install -g @graphprotocol/graph-cli```

but getting below error
```bash: graph: command not found```

### Reproduction

https://thegraph.com/hosted-service/subgraph/vishal590/nft-air-by-curious

### Steps to Reproduce the Bug or Issue

Go to 'npm install -g @graphprotocol/graph-cli'

then 'graph init --product hosted-service vishal590/nft-air-by-curious'

getting error 'bash: graph: command not found'

### Expected behavior

![fadf](https://user-images.githubusercontent.com/58502188/210133037-527794e6-7533-4e63-8a81-ea9d44a7509a.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `@graphprotocol/*` version(s): [e.g. 2.6.2]

**Comment by Bitcoinera** [comment]
Same here. Suddenly installing `graph-cli` doesn't properly work anymore

**Comment by 0xcaff** [comment]
The dist folder is missing from the latest version. https://www.npmjs.com/package/@graphprotocol/graph-cli/v/0.37.3?activeTab=explore

I worked around this by pinning 0.37.2

**Comment by Bitcoinera** [comment]
> I worked around this by pinning 0.37.2

Thank you so much! This worked wonderfully

**Comment by dotansimha** [comment]
@saihaj seems like we have an issue since latest release (after TS migration)?

**Comment by dotansimha** [comment]
@Bitcoinera @0xcaff can you please `@graphprotocol/graph-cli@0.37.4` ? (@enisdenjo fixed it in https://github.com/graphprotocol/graph-cli/releases/tag/release-1673949515173)

**Comment by ImagiNFT** [comment]
I have same issue, i tried with 0.37.4 but didn't solve it

**Comment by enisdenjo** [comment]
Sorry guys, we've just pushed [version 0.37.5](https://github.com/graphprotocol/graph-cli/releases/tag/release-1673959622911) which includes another fix. Can you please try again with the latest?

**Comment by saihaj** [comment]
tested the new release and seems to be working
