### ISSUE TITLE
Couldn't find any versions for "@graphprotocol/graph-cli" that matches "undefined"

### ISSUE THREAD

**Issue by darienmh** [graphprotocol/graph-cli#1038]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

After upgrading from version 0.37.2 to version 0.37.5 I am having the following problem when starting a project:

**`Couldn't find any versions for "@graphprotocol/graph-cli" that matches "undefined"`**

Command:

`graph init --product hosted-service --protocol ethereum --network chapel --from-contract 0x67542974739A69C72B38B11EFb84Fb0D1A8d355A graph/test --abi ./Abi.json`

![Screenshot at Jan 17 16-36-34](https://user-images.githubusercontent.com/4885186/213005921-3a9fd51d-91ae-4604-81b3-6434a907807a.png)

In the package.json file is added @graphprotocol/graph-cli with version "undefined"

![Screenshot at Jan 17 16-39-16](https://user-images.githubusercontent.com/4885186/213005956-37e4789f-f339-4265-9c38-dfd5522d3ee5.png)

___
I'm back to version 0.37.2 and I don't have this problem

![Screenshot at Jan 17 17-46-13](https://user-images.githubusercontent.com/4885186/213008818-91c17c31-73f1-45f5-bdf5-c6cad492b548.png)

The only significant change found between these two versions is the change of some files from .js to .ts

### Reproduction

https://user-images.githubusercontent.com/4885186/213005921-3a9fd51d-91ae-4604-81b3-6434a907807a.png

### Steps to Reproduce the Bug or Issue

Run command
graph init --product hosted-service --protocol ethereum --network chapel --from-contract 0x67542974739A69C72B38B11EFb84Fb0D1A8d355A graph/test --abi ./Abi.json

### Expected behavior

![Screenshot at Jan 17 17-46-13](https://user-images.githubusercontent.com/4885186/213008818-91c17c31-73f1-45f5-bdf5-c6cad492b548.png)

### Platform

- OS: macOS
- NodeJS: v16.16.0
- NPM: 9.3.0
- @graphprotocol/graph-cli : 0.37.5

**Comment by dotansimha** [comment]
@saihaj any idea if this is related to something we recently changed?

**Comment by cheeterLee** [comment]
Have met the same issue on macos11.3.1, node 18.3.1, graph-cli 0.37.5
![image](https://user-images.githubusercontent.com/87960642/213129757-08d6c450-cd0c-431d-b241-e76ba17e51b0.png)

**Comment by enisdenjo** [comment]
Hey @darienmh, we've just pushed a potential fix. Could you be so kind and test this out with the alpha release from https://github.com/graphprotocol/graph-cli/pull/1039#issuecomment-1387670593? Thanks in advance!
