### ISSUE TITLE
Save params in file for cleaner CLI usage

### ISSUE THREAD

**Issue by html5cat** [graphprotocol/graph-cli#115]
Right now running graph looks like
```
graph \
    --watch \
    --verbosity debug \
    --node $GRAPH_NODE_MANAGEMENT \
    --ipfs $GRAPH_NODE_IPFS \
    --subgraph-name my-subgraph \
    --api-key $GRAPH_NODE_API_KEY \
    deploy \
    subgraph.yaml
```

Would be nice to have an option to persist params into file so we could just run `graph deploy`

**Comment by leodasvacas** [comment]
I'd say `graph init` solved this by generating a `graph deploy` shorthand in the `package.json`.
