### ISSUE TITLE
`graph unknown-command subgraph.yaml` fails with a 'Failed to load subgraph' error

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-cli#121]
When you run
```
graph generate-types subgraph.yaml
```
or
```
graph foo subgraph.yaml
```

it fails with a `Failed to load subgraph` error, which is very confusing and incorrect. It should instead tell users that `generate-types`/`foo` is an unknown command and then probably print the usage/help text.

**Comment by wip-abramson** [comment]
Also, update docs. Step 5 tells you to paste this into your package.json
{
  "scripts": {
    "codegen": "graph **generate-types** subgraph.yaml",
    "build": "graph build subgraph.yaml",
    "build-ipfs": "graph build --ipfs /ip4/127.0.0.1/tcp/5001 subgraph.yaml"
  }
}
