### ISSUE TITLE
Add support for Solidity structs

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-cli#157]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

When structs are passed as function parameters, or return values, or emitted in an event, [the abi produced for them is actually a `tuple`](https://solidity.readthedocs.io/en/develop/abi-spec.html?highlight=tuple#mapping-solidity-to-abi-types 
). An array of structs is a `tuple[]`. This is done so that both the name and the type of the internal struct fields are available in the abi.

Right now we don't support this. It isn't a big deal right now. Since we don't support making state changing calls, we only care when calling a contract function that returns contract storage data, and it is returned as a tuple, or if an event is emitted a struct (I have yet to see an event do this, but that doesn't mean we won't come across it soon). 

Note that Neither rust web3 or web3js support it yet (web3js will be in the next version). 

Also Note, solidity has a [tuple type](https://solidity.readthedocs.io/en/develop/abi-spec.html?highlight=tuple#json), but we aren't concerned about this here. We are concerned specifically about the tuple produced in the ABI from a struct.

**But.... we still have to deal with the ABI Error**

So, if we don't support it, we should give a better error message, or else skip these functions and events all together. Right now the error is:

`Failed to generate types: Failed to generate types for contract ABIS: Error: Failed to generate types for contract ABI: Unsupported type: tuple`

I had to delete about 20 functions out of the 0x contracts, which was cumbersome, and makes the argument for skipping these. This also makes me wonder, should we really be importing the WHOLE abi ? Because this error was caused by functions I was not even using. If we required the .json file for the ABI to only contain the exact events and functions used in the subgraph, it would avoid errors as such. However, I do see that the UX of just taking the compiled abi directly from `solc` is also nice. I am unsure of which is better. I suggest leaving it as is for now. 

**How to fix this issue**
I think making the error message better should be done should be done. Skipping the functions so it doesn't error out does not provide the user with the information that events and functions from the abi were not made into types for assembly script, and so they might expect a type to exist that never got created.

**Comment by mrwillis** [comment]
Would love this feature. This is currently preventing me from using this project. 0x v2 emits structs in events and I am working on a project that makes use of this heavily. It's a shame web3js@beta still doesn't have this feature but ethers does. There's also a lot of patterns where functions return structs, and this also seems to be unsupported.

**Comment by Jannis** [comment]
Yep, we'll look into it, either by trying to contribute it to ethabi or to our own codebase.

**Comment by Jannis** [comment]
Tracked here: graphprotocol/graph-node#766.
