### ISSUE TITLE
Rare bug with types creating a duplicate identifier, causing compiling to fail

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-cli#167]
So, aragon by chance has the following two events in their ACL.sol contract

```
    event SetPermission(address indexed entity, address indexed app, bytes32 indexed role, bool allowed);
    event SetPermissionParams(address indexed entity, address indexed app, bytes32 indexed role, bytes32 paramsHash);
```
We autogenerate the following types:

```
SetPermission
SetPermissionParams
SetPermissionParams
SetPermissionParmsParams
```
This doesn't compile, because the typescript file has duplicate identifiers. (temporary fix is renaming one of the SetPermissionParams)

Maybe we should address this soon? Seems so rare. Hopefully an easy fix!

**Comment by Jannis** [comment]
Closing this in favor of #168.
