### ISSUE TITLE
Building subgraphs fails when there are overloaded events and functions

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-cli#168]
Solidity allows for multiple functions with the same name, but different arguments (overloaded functions). See https://github.com/aragon/aragonOS/blob/dev/contracts/acl/ACL.sol for a good example , they use `hasPermission` three times. 

This causes our compiler to fail because we have duplicate identifiers. 

Short term fix is rename the types created. 

What is the best way to fix this in the future? Use the function signature somehow?

**Comment by davekaj** [comment]
This might be causing errors for Aragon. They tried to build the subgraph, but got errors, but I am not sure what the error is. This would cause it to fail though for sure. We should fix this so they can use it

**Comment by Jannis** [comment]
This also needs to account for events that have the same name as the types we generate for other events, see https://github.com/graphprotocol/graph-cli/issues/167.
