### ISSUE TITLE
Generated attribute setter mishandles false boolean values

### ISSUE THREAD

**Issue by fordN** [graphprotocol/graph-cli#169]
Boolean values will have to be treated differently than other types in the generated attribute setters because boolean false is equal to null in compiled wasm.  
See https://github.com/graphprotocol/graph-node/issues/571 for information.

**Comment by Jannis** [comment]
I've investigated this briefly and wrote up my conclusion here: https://github.com/graphprotocol/graph-node/issues/571#issuecomment-446038693
