### ISSUE TITLE
Failure reading Ethereum Events with one parameter

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-cli#175]
This event: `event DeployDAO(address dao)`
Gets the following error :
```
 ERRO Subgraph instance failed to run: Failed to process event: Failed to handle
 Ethereum event with handler "handleDeployDAO": Trap: Trap { kind: Unreachable }
```
The mapping is written like so: 
```
export function handleDeployDAO(event: DeployDAO): void {
  let id = event.params.dao.toHex()
  let dao = new DAO()
  store.set("DAO", id, dao)
}
```

The type generated is : 
```
export class DeployDAOParams {
  _event: DeployDAO;

  constructor(event: DeployDAO) {
    this._event = event;
  }

  get dao(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}
```

It appears that it is trying to access element `[0]` in the array but it doesn't exist. First assumptions are that whatever is getting returned from ethereum rpc, is not actually an array, but it could just be the single address type. Could be a quirk of ethereum rpc, but it would be expected that rust-web3 would handle this. We shall investigate

**Comment by leodasvacas** [comment]
Should be solved by upgrading to latest version.
