### ISSUE TITLE
Unsafe resume flag when deploying

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-cli#218]
This would allow subgraph authors to resume failed subgraphs much faster than reindexing from scratch every time.

This needs a good design for the hosted service, so it is clear whether a subgraph may contain invalid data due to resuming.

**Comment by leodasvacas** [comment]
I still think that having a `startBlock` in the manifest would be best. It's not unsafe or incorrect and it's useful in more cases, for example if your really want your subgraph to start at a given point, or you're deploying to a new node which has not yet failed the subgraph, so it doesn't know where to resume from. But it's fine if we decide for the resume flag.

**Comment by Jannis** [comment]
Whether or not we add a `startBlock` feels like a separate issue.

Current idea:
* Add an `--unsafe-resume` flag to `graph deploy`
* Set an `unsafe` flag in the hosted service when a subgraph is deployed this way

**Comment by Jannis** [comment]
# Motivation

Subgraphs can run for a long time before failing. While developing a subgraph, it's often useful to quickly test a fix without having to wait. In order to make this possible, we're planning to add an `--unsafe-resume` flag to `graph deploy`, which allows to start indexing a new deployment from where the previous deployment failed.

# Desired behavior

1. Subgraph is deployed and eventually fails.
2. Developer runs `graph deploy ... --unsafe-resume <subgraph-name>`.
3. A new subgraph version is created as usual, but we
   1. identify the deployment hash and subgraph pointer of the previous version,
   2. we copy over all entities from the previous deployment,
   3. we initialize the new subgraph deployment with the previous deployment's subgraph block pointer
   4. we start that subgraph version

What the previous version is depends on the version switching mode:

* In `instant` mode, the previous version that we're resuming is the subgraph version that has `current` set to `true`.
* In `synced` mode:
   1. If there is a `pending` version, then this is the version that we're resuming.
   2. If there is a `current` version and it's not `synced`, then this is the version we're resuming.

# Open questions

* Copying over the entities from one deployment to another is not possible through entity operations, which is all that `create_subgraph_version` in the subgraph registrar does. Would it make sense to have something like `apply_store_operations` where a store operation can be either an entity operation or something else (e.g. a store procedure call)?

**Comment by lutter** [comment]
What I am working on for splitting up the `entities` table is to add a function `create_subgraph_deployment(ops, schema)` to the `Store`. The subgraph's `create_subgraph_version` will call that with the `ops` it collects right now, in place of `apply_entity_operations`. The `create_subgraph_deployment` will create a bunch of tables for the new subgraph, and then run the `ops` as we do today.

It seems what is needed here is to change the signature for the function to `store.create_subgraph_deployment(ops, schema, copy_from: Option<SubgraphDeploymentId>)` The registrar's `create_subgraph_version` will need to figure out if and from what other deployment to copy the data, and `create_subgraph_deployment` will then do just that.

Are we going to track that a deployment is unsafe? If so, we'll need to amend the metadata schema for subgraphs, but that is all stuff that can happen in the registrar.

**Comment by Jannis** [comment]
Yep, we'll set an `unsafe` flag for the deployment (or maybe the version).

**Comment by Jannis** [comment]
Now that we have `startBlock` on data sources (released with 0.16.0), there are probably few cases where `--unsafe-resume` will still be crucial for a fast feedback loop. We can reopen if we find it's not sufficient. For now, I am closing this issue.
