### ISSUE TITLE
EthereumTuple ERROR

### ISSUE THREAD

**Issue by tobyjaguar** [graphprotocol/graph-cli#257]
I was able to build the subgraph directory for an existing contract but receive the following error when trying to deploy:

`Compile subgraphERROR TS2305: Module '~lib/@graphprotocol/graph-ts' has no exported member 'EthereumTuple'.`

The build error logs:
```
EthereumTuple,
   ~~~~~~~~~~~~~
 in generated/Contract/Contract.ts(8,2)

ERROR TS2377: Constructors for derived classes must contain a 'super' call.

 export class Entity extends TypedMap<string, Value> {
  constructor() {
    this.entries = new Array<TypedMapEntry<string, Value>>(0)
  }
                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in ~lib/@graphprotocol/graph-ts/index.ts(810,53)

✖ Failed to compile subgraph: Failed to compile data source mapping: Compile error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This contract uses the experimental `ABIEncoderV2` in which we return structs.
Is this feature supported with thegraph?

**Comment by PaulRBerg** [comment]
Structs don't seem to be supported: https://github.com/graphprotocol/graph-node/issues/766

**Comment by PaulRBerg** [comment]
In my case, I got this error output:

```
ERROR TS2305: Module '~lib/@graphprotocol/graph-ts' has no exported member 'EthereumTuple'.

   EthereumTuple,
   ~~~~~~~~~~~~~
in src/types/Sablier/Sablier.ts(8,2)

ERROR TS2377: Constructors for derived classes must contain a 'super' call.

export class Entity extends TypedMap<string, Value> {
  constructor() {
    this.entries = new Array<TypedMapEntry<string, Value>>(0)
}
                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in ~lib/@graphprotocol/graph-ts/index.ts(810,53)
```

I'm not using the ABIEncoderV2 so I don't think this should fail. I am, though, instantiating structs in my [contract][streams-contract]'s constructor.

My environment:

- macOS
- @graphprotocol/graph-cli 0.10.0
- @graphprotocol/graph-ts 0.6.0

Also tried downgrading the versions but had the exact same issues.

[streams-contract]: https://github.com/SablierApp/monorepo/blob/develop/packages/contracts/contracts/streams/Streams.sol

**Comment by PaulRBerg** [comment]
Going down the rabbit hole, I noticed that the Gravity contract from the [example subgraph][example-subgraph] handles structs:

```solidity
struct Gravatar {
    address owner;
    string displayName;
    string imageUrl;
}
...
uint id = gravatars.push(Gravatar(msg.sender, _displayName, _imageUrl)) - 1;
```

I'm doing something similar, but with a slightly different syntax:

```solidity
streams[streamNonce] = Stream({
    sender : _sender,
    recipient : _recipient,
    tokenAddress : _tokenAddress,
    balance : deposit,
    timeframe : Timeframe(_startBlock, _stopBlock),
    rate : Rate(_payment, _interval)
});
```

Maybe rewriting the contract to not use these key/value pairs will do the trick. I'll update this comment as I plunge through.

[example-subgraph]: https://github.com/graphprotocol/example-subgraph/tree/master/contracts

**Comment by PaulRBerg** [comment]
I figured it out. In the `aefe058d2b5481240ee544d3d580d2848a6baf73` commit, they introduced a few changes:

- [Added and renamed the `Tuple` type to `EthereumTuple`](https://github.com/graphprotocol/graph-ts/blob/aefe058d2b5481240ee544d3d580d2848a6baf73/index.ts)
- [Bumped the package version from 0.6.0 to 0.10.0](https://github.com/graphprotocol/graph-ts/blob/aefe058d2b5481240ee544d3d580d2848a6baf73/package.json)

Therefore, it follows that when you're using the graph CLI to bootstrap a new subgraph from your deployed contracts, the dependency version of both `@graphprotocol/graph-cli` and `@graphprotocol/graph-ts` should be in sync.

However, they are NOT, because both I and likely @tobyjaguar too had `0.6.0` instead of `0.10.0` for the TypeScript repo.

So doing `yarn add @graphprotocol/graph-ts@0.10.0` or `npm install @graphprotocol/graph-ts@0.10.0` fixes the EthereumTuple error. This should also be mended in the CLI tool itself.

**Comment by elopio** [comment]
Worked for me, thanks @PaulRBerg.

**Comment by tobyjaguar** [comment]
Oh, great. If this is the fix that would be amazing. Thanks for looking into this @PaulRBerg. I will report back when I get a chance to look into this.

**Comment by tobyjaguar** [comment]
@PaulRBerg I was able to deploy the graph based on an existing contract. Thank you much!

**Comment by Jannis** [comment]
Appreciate the deep dive, @PaulRBerg — thanks!

**Comment by leodasvacas** [comment]
@Jannis I don't think this is fixed, we generate scaffolds with graph-ts version 0.6, which should be 0.10:
https://github.com/graphprotocol/graph-cli/blob/124d31023d31b9fd2b1f3504edfa722366be9bbc/src/scaffold.js#L37
