### ISSUE TITLE
codegen mistakenly generates cast from 'FixedBytes' instead of 'Bytes'

### ISSUE THREAD

**Issue by Arachnid** [graphprotocol/graph-cli#284]
I have a contract function with the following signature:

```
  function computeClaimId(claimed string, dnsname bytes);
```

When codegen is run on it, it generates this function:

```
  computeClaimId(claimed: string, dnsname: Bytes): Bytes {
    let result = super.call("computeClaimId", [
      EthereumValue.fromString(claimed),
      EthereumValue.fromFixedBytes(dnsname)
    ]);
    return result[0].toBytes();
  }
```

Clearly line 4 should read `EthereumValue.fromBytes(dnsname)`.

**Comment by leodasvacas** [comment]
@Arachnid Is there a contract on mainnet or testnet, or just an abi file, that we can use to reproduce?

**Comment by Arachnid** [comment]
Sure! The contract is here: https://github.com/ensdomains/ethregistrar/blob/master/contracts/ShortNameClaims.sol

It's deployed on Ropsten at 0xd5be10a138550bd8b53b986af2e45901f377e2bb.
