### ISSUE TITLE
Problem with deploy

### ISSUE THREAD

**Issue by anthonymq** [graphprotocol/graph-cli#341]
Hello,
This seems stupid but i can't deploy with the graph-cli.
Each time I try I have this message :
`Graph node "http://127.0.0.1:8020" is invalid: URL is not defined`
It seems that validateNodeUrl fires this exception (https://github.com/graphprotocol/graph-cli/blob/master/src/commands/deploy.js#L99)
But I can't figure out why.
Any help ?

**Comment by akeem** [comment]
Hi @anthonymq , I came across your post after encountering the same issue. My issue was attributed to me running node 8, I believe using node v10 may help here (the information was gathered from a search of the graph's discord)

**Comment by anthonymq** [comment]
@akeem It worked ! Thank you !
