### ISSUE TITLE
Supporting multi-dimensional arrays for type creation

### ISSUE THREAD

**Issue by samparsky** [graphprotocol/graph-cli#342]
I have a solidity contract with the below definition
```
contract Test {
    function test( bytes32[3][] len) 
     public 
    {
        
    }
}
```
Running 
```
graph init --from-contract 0xe6A... --network kovan --abi ./test.json test/test-subgraph
```
generates the below error

```
Failed to generate types for contract ABIs: Failed to generate types for contract ABI: Conversion from 'EthereumValue' to 'AssemblyScript' for source type 'bytes32[3][]' is not supported
error Command failed with exit code 1.
```

**Comment by davekaj** [comment]
Hey @samparsky ,

Yes we don't support this yet. We need to add in support for dimensional arrays to `graph-cli`. We will talk about it in the next team meeting and determine when we can add support! In the mean time if you must move forward, I suggest leaving out these types if possible from your subgraph.

**Comment by davekaj** [comment]
![Screen Shot 2019-09-28 at 3 17 34 PM](https://user-images.githubusercontent.com/22417382/65821666-8032ba00-e206-11e9-8504-573c7c7f5cc7.png)

Justin from synthetix has also ran into this

**Comment by leoyvens** [comment]
Took the liberty of pre-assigning @fordN who knows more about this. @Jannis lets try to triage this on our next planning meeting.

**Comment by wslyvh** [comment]
Any update on this one? I was working on a graph as well that requires multi-dimensional arrays (uint256[][]).

**Comment by jacobrosenthal** [comment]
My problem is the same but also adds another case, the return position
```
    function getUpgrades()
        public
        view
        returns (DarkForestTypes.Upgrade[4][3] memory)
    {
...
    }
```

**Comment by alphak3y** [comment]
For anyone reading this now...

Make sure you **remove** the section with the 2d array from your ABI before you run `yarn codegen`.

As long as you do not use the function, event, etc. in your Subgraph mapping handlers, you will be fine.

Cheers!

**Comment by mzhu25** [comment]
Any solution if I _do_ need an event that has an array of structs?

**Comment by manumonti** [comment]
Any update on this?

**Comment by sunny0714** [comment]
graph init --from-contract 0x472b5B62d5F27668952a7Da55F57F4004699ae9D --protocol ethereum \ --network rinkeby --contract-name ERC721 --index-events
When I run this, I get this error message
Failed to create subgraph scaffold: Conversion from 'AssemblyScript' to 'Value' for source type 'Array<ethereum.Tuple>' is not supported

When will this be supported?
or is there any way to avoid this error?

**Comment by azf20** [comment]
Hi @sw0714 I think this was fixed here? https://github.com/graphprotocol/graph-cli/issues/862
cc @evaporei

**Comment by hbriese** [comment]
@azf20 Getting `Failed to generate types for contract ABIs: Failed to generate types for contract ABI: Conversion from 'ethereum' to 'AssemblyScript' for source type 'address[][]' is not supported` on 0.33.0

**Comment by peripheralist** [comment]
any progress on this?

would it be reasonable to allow typing these as `unknown` and writing a custom parser in mappings?

**Comment by hbriese** [comment]
My current (terrible) workaround is to abi encode the internal array i.e. Address[][] -> Bytes[], and decode it in the subgraph

**Comment by peripheralist** [comment]
> My current (terrible) workaround is to abi encode the internal array i.e. Address[][] -> Bytes[], and decode it in the subgraph. @peripheralist at least this would allow a workaround without require contract-level changes

yeah, i'll probably end up doing something like that. though it'd be nice to avoid making contract-level changes based on off-chain infrastructure 😑

**Comment by mbartn** [comment]
> My current (terrible) workaround is to abi encode the internal array i.e. Address[][] -> Bytes[], and decode it in the subgraph. @peripheralist at least this would allow a workaround without require contract-level changes

Could you give an example snippet of how you do it?

**Comment by evaporei** [comment]
I'm currently working/implementing this 😊

**Comment by evaporei** [comment]
I'm getting closer to the testing phase 🎉  if possible could any of you please give example contract addresses so I can test it? 🙂

**Comment by evaporei** [comment]
I'm getting closer to the testing phase 🎉  if possible could any of you please give example contract addresses so I can test it? 🙂 

@samparsky @wslyvh @jacobrosenthal @liaopeiyuan @alphak3y @manumonti @hbriese @peripheralist @mbartn

**Comment by GabrielCamba** [comment]
Hey @evaporei 0x9008D19f58AAbD9eD0D60971565AA8510560ab41 this address contains a tuple[][3] that prevents to index the settle contract call. 
This address is deployed both on mainnet and gnosis chain.

**Comment by manumonti** [comment]
> 

Hi @evaporei 

I found this multi-dimensional array limitation with this contract:

https://github.com/nucypher/nucypher-contracts/blob/710b68713b5b8fece0d0b1c5de376dba1d7d68e7/contracts/contracts/SimplePREApplication.sol#L114

Deployed on mainnet: "address": "0x7E01c9c03FD3737294dbD7630a34845B0F70E5Dd"

**Comment by dmihal** [comment]
@evaporei The CowSwap contract (`0x9008d19f58aabd9ed0d60971565aa8510560ab41`) has one

**Comment by evaporei** [comment]
Hey folks I just released an alpha version of each project (CLI and TS) that I'm testing with those contracts, if you guys want to check them out too and bring any possible problems that you've faced with it:

- https://www.npmjs.com/package/@graphprotocol/graph-cli/v/0.34.0-alpha.0
- https://www.npmjs.com/package/@graphprotocol/graph-ts/v/0.28.0-alpha.0

**Comment by GabrielCamba** [comment]
Hey @evaporei !
I've been trying to index `0x9008D19f58AAbD9eD0D60971565AA8510560ab41` settle call that includes `tuple[][3]` 
The [code](https://github.com/GabrielCamba/multidimensionalArraysPOC) (where it's just counting calls) is already deployed [here](https://thegraph.com/hosted-service/subgraph/gabrielcamba/gpv2poc) and unfortunately there's no call indexed. 
Please let me know if I'm missing something or if I'm doing something wrong.

**Comment by azf20** [comment]
thanks @evaporei!
@GabrielCamba can you share a link to a transaction including a `settle` call which we can take a look at?

**Comment by evaporei** [comment]
This is now done and available at these CLI and TS versions 😉 🎉 

- https://www.npmjs.com/package/@graphprotocol/graph-cli/v/0.34.0
- https://www.npmjs.com/package/@graphprotocol/graph-ts/v/0.28.0

**Comment by illestrater** [comment]
Hi @evaporei looks like I'm running into an issue.

I'm successfully able to use codegen and write my handlers fine, but getting an error on build specifically on the multidimensional arrays. Typescript is showing the error for the generated schema as well.

```
ERROR TS2339: Property 'fromStringMatrix' does not exist on type '~lib/@graphprotocol/graph-ts/common/value/Value'.

     this.set("values", Value.fromStringMatrix(value));
                              ~~~~~~~~~~~~~~~~
 in generated/schema.ts(1300,30)

ERROR TS2339: Property 'fromBigIntMatrix' does not exist on type '~lib/@graphprotocol/graph-ts/common/value/Value'.

     this.set("valuesChance", Value.fromBigIntMatrix(value));
                                    ~~~~~~~~~~~~~~~~
 in generated/schema.ts(1318,36)
```

Here's the generated code snippet:

```
get values(): Array<Array<string>> {
    let value = this.get("values");
    return value!.toStringArray();
  }

  set values(value: Array<Array<string>>) {
    this.set("values", Value.fromStringMatrix(value));
  }
```

**Comment by illestrater** [comment]
I was able to compile & build by copying the matrix functions from ethereum.ts to value.ts - I believe these functions should exist in value.ts?

Now I'm facing a runtime issue:

`Entity Canvas[1]: field `values` is of type [[String!]!]!, but the value `[[Elevated, Sublime, Majestic, Royal, Utopian, Psychedelic, Divine]]` contains a [String] at index 0 wasm backtrace: 0: 0x3429`

Is this the correct syntax to support a multi-dimensional array within the schema?

**Comment by evaporei** [comment]
@illestrater are you sure you did an upgrade to your `graph-ts` library? Since the `Matrix` functions are not being found, this means you're using an older version which didn't include those.

**Comment by illestrater** [comment]
Hi @evaporei it seems like the matrix functions are indeed missing in the graph-ts library: https://github.com/graphprotocol/graph-ts/blob/main/common/value.ts

Codegen created dependencies for common/value.ts rather than chain/ethereum.ts where the matrix functions live

**Comment by evaporei** [comment]
I'll take a look at this over this weekend 🙂

**Comment by evaporei** [comment]
@illestrater you're right, I'll do a patch with those functions, thanks for the report!

@anxolin do you know a transaction for this contract where a `settle` call happens so we can debug it?

**Comment by evaporei** [comment]
@illestrater can you please try again with versions `0.28.1` and `0.34.1` please?

**Comment by alfetopito** [comment]
> @anxolin do you know a transaction for this contract where a `settle` call happens so we can debug it?

Same as what @GabrielCamba shared before:

https://github.com/graphprotocol/graph-cli/issues/342#issuecomment-1242533424
https://github.com/graphprotocol/graph-cli/issues/342#issuecomment-1245488571

For a more recent tx, see here https://etherscan.io/tx/0x37d02419e8466e64c9dc60dc67fde2ecfe21ae872e814d7992d5ff128a30f74f

For reference of the events emitted https://github.com/cowprotocol/contracts/blob/main/src/contracts/GPv2Settlement.sol#L50-L68

**Comment by alfetopito** [comment]
> Hello @alfetopito ! I've made a [fork](https://github.com/evaporei/multidimensionalArraysPOC) of @GabrielCamba 's subgraph to Ethereum `mainnet`, and set the `startBlock` at the transaction you've sent and my local `graph-node` at `master` processed it correctly 🎉
> 
> ```
> Oct 21 14:03:33.767 INFO Done processing trigger, gas_used: 172528289, data_source: GPv2Settlement, handler: handleSettle, total_ms: 33, transaction: 0x3092…38bc, to: 0x9008…ab41, function: settle(address[],uint256[],(uint256,uint256,address,uint256,uint256,uint32,bytes32,uint256,uint256,uint256,bytes)[],(address,uint256,bytes)[][3]), sgd: 16, subgraph_id: QmXqo5ojpVnkWNVnf3z5q5J17hrbogz6hZF1oZGq6kv3x7, component: SubgraphInstanceManager
> Oct 21 14:03:33.773 INFO Applying 2 entity operation(s), block_hash: 0x98b9ca11d873416ce6f805b9a3e05bbd6d2fbf678b68a45257c4b0f46301303a, block_number: 15775739, sgd: 16, subgraph_id: QmXqo5ojpVnkWNVnf3z5q5J17hrbogz6hZF1oZGq6kv3x7, component: SubgraphInstanceManager
> ```
> 
> So it should be working normally at the Hosted Service, are you use that you're using the most recent `graph-cli` and `graph-ts`?

Thanks for your reply, @evaporei 

We've tried last with:

```
"dependencies": {
    "@graphprotocol/graph-cli": "0.34.0",
    "@graphprotocol/graph-ts": "0.28.0"
  },
```

While you tested with:

```
  "dependencies": {
    "@graphprotocol/graph-cli": "0.35.0",
    "@graphprotocol/graph-ts": "0.28.1"
  },
```

We'll try with `graph-cli` 0.35.0 and `graph-ts` 0.28.1 and report back

**Comment by damianlluch** [comment]
I have this problem!

Any updates?

**Comment by alxlacayo** [comment]
> Entity Canvas[1]: field `values` is of type [[String!]!]!, but the value `[[Elevated, Sublime, Majestic, Royal, Utopian, Psychedelic, Divine]]` contains a [String] at index 0 wasm backtrace: 0: 0x3429

Having this issue also, did you find a solution?

` field `barrels` is of type [[BigInt!]!]!, but the value `[[1, 2, 0, 3, 3, 2, 3, 1, 3, 3, 2, 3, 2, 3, 3], [2, 3, 1, 2, 3, 3, 3, 3, 1, 3, 2, 0, 3, 2, 3], [1, 3, 2, 3, 2, 3, 3, 1, 3, 2, 3, 2, 3, 0, 3]]` contains a [BigInt] at index 0 wasm `

**Comment by NanezX** [comment]
> > Entity Canvas[1]: field `values` is of type [[String!]!]!, but the value `[[Elevated, Sublime, Majestic, Royal, Utopian, Psychedelic, Divine]]` contains a [String] at index 0 wasm backtrace: 0: 0x3429
> 
> Having this issue also, did you find a solution?
> 
> `field`barrels`is of type [[BigInt!]!]!, but the value`[[1, 2, 0, 3, 3, 2, 3, 1, 3, 3, 2, 3, 2, 3, 3], [2, 3, 1, 2, 3, 3, 3, 3, 1, 3, 2, 0, 3, 2, 3], [1, 3, 2, 3, 2, 3, 3, 1, 3, 2, 3, 2, 3, 0, 3]]`contains a [BigInt] at index 0 wasm`

Having the same issue than you. Any solution to this?
