### ISSUE TITLE
Graph CLI to accept argument to path of subgraph.yaml

### ISSUE THREAD

**Issue by justinjmoses** [graphprotocol/graph-cli#359]
We use the same subgraph repo for a number of similar subgraphs. Yet the CLI is limited in that it expects a file `./subgraph.yaml` in the root of the repo. In order to support our workflow, we'd like the path to the `yaml` file to be optionally provided to `graph-cli` as an argument. This applies to the `build`, `codegen` and `deploy` actions. 

This is how we're currently working around the limitation. https://github.com/Synthetixio/synthetix-subgraph/blob/master/package.json#L10-L13

**Comment by leoyvens** [comment]
@justinjmoses We already allow you to specify a path to `subgraph.yaml`, simply do `graph build /path/to/subgraph.yaml`. However I did notice some bugs while testing this, which should be fixed in #360.

**Comment by justinjmoses** [comment]
Can this be released with a new CLI version?

**Comment by Jannis** [comment]
@justinjmoses Done!

NPM: https://www.npmjs.com/package/@graphprotocol/graph-cli/v/0.15.1
GitHub: https://github.com/graphprotocol/graph-cli/releases/tag/v0.15.1

**Comment by leoyvens** [comment]
I'm re-opening this because the question of how to make AS resolve `"@graphprotocol/graph-ts"` when `subgraph.yaml` is not in the same directory as `node_modules` remains an open question. An option is to have an additional cli option for the path to `node_modules` that serves as the `--lib` option to the AS compiler.

**Comment by justinjmoses** [comment]
@leoyvens can you release a new patch of the CLI?

**Comment by leoyvens** [comment]
@Jannis

**Comment by Jannis** [comment]
v0.15.2 has been released just now.
