### ISSUE TITLE
Support generating types for overloaded functions

### ISSUE THREAD

**Issue by adklempner** [graphprotocol/graph-cli#44]
[`LANDRegistry`](https://github.com/decentraland/decentraland-eth/blob/master/src/contracts/artifacts/LANDRegistry.json#L823) has two functions with the name `exists` but with different param types. Running `yarn codegen` produces this error:

```ts
ERROR TS2300: Duplicate identifier 'index/LANDRegistry#exists'.

   exists(assetId: U256): bool {
   ~~~~~~
 in index.ts(693,2)
```

**Comment by Jannis** [comment]
This was fixed with #252.
