### ISSUE TITLE
[Bug] - Wrong events order

### ISSUE THREAD

**Issue by rotcivegaf** [graphprotocol/graph-cli#441]
I heard the events of `0xb2403dca04ab49492e1e05b29f26e6c01ac5d604`, address of debtEngine contract

And, I have this tx: `0xbfc71b421f37bca4c2ba01df5fbc9be40f1420019f6e2aa2d7eb530b330e495a`

In this tx there are three event of debEngine contract:

  1. Event: `Transfer(address,address,uint256)` with topic0: `0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef`

  2. Event: `Created2(bytes32,uint256,bytes)` with topic0: `0x4ee48d90c05f58fc51a05728e403947a51e36cc7a1bf4d82260473b433538408`

  3. Event: `Transfer(address,address,uint256)` with topic0: `0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef`

But when run graph, the order of the events its wrong, the Created2 goes first....

**Comment by leoyvens** [comment]
Thanks for the report @rotcivegaf, if possible could you provide a link to the subgraph source (if it is open source), and a link to the events on Etherscan, with the order you observe vs the order you expect?

**Comment by rotcivegaf** [comment]
It was my mistake
The error was in my code, I'm sorry
It also costs a lot to debug the code especially because you cannot make a log of an object and the logs have to be of the String type, casting everything to string becomes more complex everything
