### ISSUE TITLE
[Help] - BinInt to Bytes

### ISSUE THREAD

**Issue by rotcivegaf** [graphprotocol/graph-cli#442]
I have this

```
type Example @entity {
    id: ID!
    owner: Bytes! # address
}
```

I new an Example with a Bytes32 recieve from an X event, this Bytes32 represents the identifiear of an erc721 token, and save it, for example:

`0x84eab1e0f7ed8e163d2b259f5a7b7998bfe7c1bdfb012e70177e1cad8b898c9`

Later recieve the clasic ERC721 event `Transfer(address,address,uint256)`

And i try this:
```
export function handleTransfer(event: Transfer): void {
  let example = Example.load(event.params._tokenId.toHexString())
  example.owner = event.params._to.toHexString();
  example.save();
}
```

The grapth cant find the example, I think

I want transform the BigInt(_tokenId) to Bytes32, this is correct `event.params._tokenId.toHexString()`?

**Comment by leoyvens** [comment]
@rotcivegaf it would help to have a link to a branch or commit with a runnable subgraph. Also this type of question is better suited for Discord, so we can continue the conversation there if you prefer.

**Comment by rotcivegaf** [comment]
[Subgraph](https://thegraph.com/explorer/subgraph/rotcivegaf/rcn_api?selected=logs)
[github repo](https://github.com/rotcivegaf/TheGraphExample)

**Comment by leoyvens** [comment]
I see you switched the `Owner` type to `String` so you can store the address as hex string. That works, if you wanted to keep it as `Bytes` you could do simply:
```
example.owner = event.params._to
```

**Comment by rotcivegaf** [comment]
Please look this lines:
- https://github.com/rotcivegaf/TheGraphExample/blob/72586cf788b6a5b7fea31f2bd8b97220cdba65bf/src/debtEngineMapping.ts#L49
- https://github.com/rotcivegaf/TheGraphExample/blob/72586cf788b6a5b7fea31f2bd8b97220cdba65bf/src/debtEngineMapping.ts#L179
- https://github.com/rotcivegaf/TheGraphExample/blob/72586cf788b6a5b7fea31f2bd8b97220cdba65bf/src/debtEngineMapping.ts#L184

And look the error in web of the graph

**Comment by leoyvens** [comment]
As quick feedback from looking at the error, make sure to check the input to `Debt.load` and `new Debt` for null so you don't create an entity with no id.

**Comment by rotcivegaf** [comment]
In the contract, the event Transfer goes first, second goes the event Created and the created its unique(emit only one time)
If the from param of event Transfer its the address 0, that means what the Debt its not exsists and the transfer hanndler returns, otherwise load the debt and change the owner
If the from param of event Transfer its the address 0, the next event(the Created) will create the Debt

Specified that, I have four question, and please respond with a code if it's possible

1. How transform a Bytes(bytes32) to a BigInt(uinr256), what can call the ownerOf function on standard ERC721
2. It this a correct evaluation: `event.params._from.toHex() == '0x0000000000000000000000000000000000000000'`?
3. Viceversa of the first, How transform a BigInt(uint256) to a Bytes(bytes32), what can load the Debt
4. Why my code throw and error 
Look in [Subgraph](https://thegraph.com/explorer/subgraph/rotcivegaf/rcn_api?selected=logs), pending version, logs and error or warnings
```
Subgraph instance failed to run: Failed to process trigger in block #6451311 (b6f3d954d1ea91faa445449bceb18096b809a3f415879a37b8b61dc051271f8a), transaction bfc71b421f37bca4c2ba01df5fbc9be40f1420019f6e2aa2d7eb530b330e495a: Failed to handle Ethereum event with handler "handleTransfer": Mapping aborted at generated/schema.ts, line 200, column 4, with message: Cannot save Debt entity without an ID, code: SubgraphSyncingFailure, id: QmeV5vJfXetUahpQ7T41qdaXdp8TJsCaVaQc4d3eCajEvp
```

**Comment by Jannis** [comment]
Please join our Discord on https://thegraph.com/discord/ for support requests.
