### ISSUE TITLE
Generated function result for tuple is of undefined type

### ISSUE THREAD

**Issue by JamesLefrere** [graphprotocol/graph-cli#455]
Hi, I'm having a problem with the ABI code generator where a tuple type doesn't seem to be processed correctly, and it leads to AssemblyScript errors.

See this gist: https://gist.github.com/JamesLefrere/40a7b4f6bfa0f050548faaebc1ee689f

I believe the problem occurs here in the generator: https://github.com/graphprotocol/graph-cli/blob/fa6707600be19f378ddff60757f79300f9ae86f8/src/codegen/abi.js#L247

The third argument should be the type, but it wasn't provided. 

I'm not entirely sure what the expected behaviour should be here... any ideas?

Cheers

**Comment by leoyvens** [comment]
@JamesLefrere Thank you for the report. Would it be possible to provide a full subgraph on which this can be reproduced?

Pinging @fordN who added tuple support.

**Comment by JamesLefrere** [comment]
Hey @leoyvens @fordN thanks for the quick response. I can't provide a full subgraph at the moment, but it's fairly easy to reproduce; just define a function like the gist with a tuple array of structs.

I've just created #456 which resolves the issue (at least, for me) :tada:
