### ISSUE TITLE
Implement Token.fromI{8,16,32,64} and Token.fromU{8,16,32,64}conversions

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-cli#48]
These need to convert the little-endian representations of i8, i16, i32, i64, u8, u16, u32, u64 to big-endian representations of I256 and U256.

**Comment by Jannis** [comment]
@leodasvacas Is this still up to date? We should either do this or close the issue.

**Comment by leodasvacas** [comment]
Since this is old the motivation is no longer clear, but our store for now only support `i32` and we have `fromI32` and `toI32`. Perhaps this was about also supporting different integer types on the store? We need to re-discuss the requirements here.

**Comment by Jannis** [comment]
This is about being able to pass `u8`, `u32` etc. to smart contract calls and read `u8`, `u32` etc. from events and call results. It's less about what we support in the store / entity attributes.

**Comment by leodasvacas** [comment]
Ah then it's about `EthereumValue` rather than `Token`. That seems like exactly what I'm fixing right now.
