### ISSUE TITLE
Unable to install graph-cli

### ISSUE THREAD

**Issue by dackjaniels2001** [graphprotocol/graph-cli#565]
Attempting to run `npm install -g @graphprotocol/graph-cli` in Windows 10 command prompt results in the following output

`npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142`

I see the npm 'progress bar' but it never moves, it just appears stuck.

After googling the error I also tried

`npm install -g --unsafe-perm=true --allow-root @graphprotocol/graph-cli --registry https://testnet.thegraph.com/npm-registry/`

but this result in the following output

```
npm ERR! code E401
npm ERR! 401 Unauthorized: @graphprotocol/graph-cli@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dackj\AppData\Roaming\npm-cache\_logs\2020-10-24T20_35_23_892Z-debug.log
```

How can I install the graph-cli on Windows?

Thanks

**Comment by dackjaniels2001** [comment]
An update to say that after deleting the @graphprotocol folder from node_modules in appdata and running the npm install command again I immediately saw the downloads and installation progressing.

I now see one error in the output though I'm not sure yet if this will affect the functionality of the graph-cli:

```
\AppData\Roaming\npm\node_modules\@graphprotocol\graph-cli\node_modules\secp2
56k1\build\secp256k1.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.D
efault.props" was not found. Confirm that the path in the <Import> declaration is correct,
and that the file exists on disk.
```

**Comment by DengKaiSheng** [comment]
Have you solved the problem

**Comment by DengKaiSheng** [comment]
I had the same problem

**Comment by AndoGhevian** [comment]
I used nvm to switch to node 11.x version and it works, I encountered this version number in their [Installation on different operating systems](https://github.com/graphprotocol/graph-cli/wiki/Installation-on-different-operating-systems). NOTE: I use Ubuntu.

**Comment by Wakuangdachengzi** [comment]
I had the same problem，Have you solved the problem？

**Comment by AndoGhevian** [comment]
@Wakuangdachengzi They just use **version 11 of node** and an appropriate **version of npm**, you need to switch to that version in terminal from which you perform installation. -
```
nvm install 11
nvm use 11
npm install -g @graphprotocol/graph-cli
```
This command will also switch to appropriate npm version.
It seems there was behavior of npm which is currently deprecated for newer versions, or there is some node runtime breaking changes exists, so installation hanging around without any warnings.
You can see this version mentioned in here - [Installation on different operating systems](https://github.com/graphprotocol/graph-cli/wiki/Installation-on-different-operating-systems)

**Comment by juliencarponcy** [comment]
Originally had same issue, now switched on ubuntu and have others.
Please keep informed

**Comment by schmidsi** [comment]
We updated graph-cli to version 0.20.1 recently. Can you please try again and see if your issue is now resolved?

**Comment by nissoh** [comment]
perhaps unrelated, but i'm having permission issues while trying to install `graph-cli` globally using this cmd `sudo npm install -g @graphprotocol/graph-cli`

Macbook Pro M1, here's log
````
nisko@Nissans-MacBook-Pro ~> sudo npm install -g @graphprotocol/graph-cli
Password:
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated promisify-es6@1.0.3: Unmaintained
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated multicodec@0.5.7: stable api reached
npm WARN deprecated libp2p-crypto-secp256k1@0.3.1: Included in libp2p-crypto, use it instead. https://github.com/libp2p/js-libp2p-crypto
npm WARN deprecated peer-info@0.15.1: No longer supported for js-libp2p0.28.0 or later
npm ERR! code 243
npm ERR! git dep preparation failed
npm ERR! command /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/nisko/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code EACCES
npm ERR! npm ERR! syscall symlink
npm ERR! npm ERR! path ../../../../Users/nisko/.npm/_cacache/tmp/git-clone-1ceba514
npm ERR! npm ERR! dest /usr/local/lib/node_modules/assemblyscript
npm ERR! npm ERR! errno -13
npm ERR! npm ERR! Error: EACCES: permission denied, symlink '../../../../Users/nisko/.npm/_cacache/tmp/git-clone-1ceba514' -> '/usr/local/lib/node_modules/assemblyscript'
npm ERR! npm ERR!  [Error: EACCES: permission denied, symlink '../../../../Users/nisko/.npm/_cacache/tmp/git-clone-1ceba514' -> '/usr/local/lib/node_modules/assemblyscript'] {
npm ERR! npm ERR!   errno: -13,
npm ERR! npm ERR!   code: 'EACCES',
npm ERR! npm ERR!   syscall: 'symlink',
npm ERR! npm ERR!   path: '../../../../Users/nisko/.npm/_cacache/tmp/git-clone-1ceba514',
npm ERR! npm ERR!   dest: '/usr/local/lib/node_modules/assemblyscript'
npm ERR! npm ERR! }
npm ERR! npm ERR! 
npm ERR! npm ERR! The operation was rejected by your operating system.
npm ERR! npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! npm ERR! 
npm ERR! npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! npm ERR! permissions of the file and its containing directories, or try running
npm ERR! npm ERR! the command again as root/Administrator.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/nisko/.npm/_logs/2021-07-08T17_27_15_078Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nisko/.npm/_logs/2021-07-08T17_27_15_784Z-debug.log
````

**Comment by pranavdaa** [comment]
<img width="920" alt="Screenshot 2021-07-09 at 12 16 29 AM" src="https://user-images.githubusercontent.com/38764142/124974855-eccd2080-e04a-11eb-86c0-5f0cc0dc93c4.png">
I also have a mac M1 and it works for me.

Node version- v14.17.1
npm version - 6.14.13

Let me know if it works after the update on the versions may be

**Comment by nissoh** [comment]
> <img alt="Screenshot 2021-07-09 at 12 16 29 AM" width="920" src="https://user-images.githubusercontent.com/38764142/124974855-eccd2080-e04a-11eb-86c0-5f0cc0dc93c4.png">
> 
> I also have a mac M1 and it works for me.
> Node version- v14.17.1
> npm version - 6.14.13
> 
> Let me know if it works after the update on the versions may be

@pranavdaa thanks for the reply, it seems like there were some dir permissions that i have had to allow, running these cmd's helped

```
sudo chown -R $USER /usr/local/lib/node_modules/
sudo chown -R $USER /usr/local/bin/
sudo chown -R $USER /usr/local/share/
```
