### ISSUE TITLE
Subgraph removing error : Removing subgraphs is not supported at this time.

### ISSUE THREAD

**Issue by ssilvajb** [graphprotocol/graph-cli#584]
I tried to remove a subgraph and the command shows an error explaining the operation is not supported

graph -v 
0.19.0

graph remove <USER>/<NAME> --node https://api.thegraph.com/deploy/
✖ Error removing the subgraph: Removing subgraphs is not supported at this time.

**Comment by leoyvens** [comment]
@ssilvajb please ask in our Discord and we will be able to remove the subgraph for you.
