### ISSUE TITLE
Invalid account name or access token while using --access-token in graph deploy

### ISSUE THREAD

**Issue by jdkanani** [graphprotocol/graph-cli#599]
Following command throwing error even if `--access-token` value is correct: `Invalid account name or access token` 

```
graph deploy --access-token <access-token> ....
```

**Comment by westdabestdb** [comment]
@jdkanani Did you manage to solve the issue?

**Comment by TimDaub** [comment]
what's the solution here?

**Comment by TimDaub** [comment]
For me the problem was that I had accidentally tried to deploy my subgraph to someone else's hosted service

```
graph deploy --product hosted-service anothercompany/theirsubgraph
```
