### ISSUE TITLE
Subgraph with lots of data failed to be uploaded to IPFS

### ISSUE THREAD

**Issue by wighawag** [graphprotocol/graph-cli#600]
Deploying a subgraph where one of the source file (generated from some data) is 3.6 MB

I get the following error :

```
× Failed to upload subgraph to IPFS: Failed to upload file to IPFS: <html>
<head><title>413 Request Entity Too Large</title><script src="/cdn-cgi/apps/head/a-7iaLT0SRdb_kvxGKIYLrjkGzU.js"></script></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.19.5</center>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"rayId":"60e5b913dad53732","version":"2020.12.2","si":10}'></script>
</body>
</html>

Error: Failed to upload file to IPFS: <html>
<head><title>413 Request Entity Too Large</title><script src="/cdn-cgi/apps/head/a-7iaLT0SRdb_kvxGKIYLrjkGzU.js"></script></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.19.5</center>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"rayId":"60e5b913dad53732","version":"2020.12.2","si":10}'></script>
</body>
</html>

    at Compiler._uploadToIPFS (C:\dev\test\subgraph\node_modules\@graphprotocol\graph-cli\src\compiler.js:613:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "mainnet:redeploy" exited with 1.
error Command failed with exit code 1.
```

**Comment by leoyvens** [comment]
The limit was increased please try again.

**Comment by wighawag** [comment]
getting this error now :

```
Failed to deploy to Graph node https://api.thegraph.com/deploy/: subgraph resolve error: resolve error: IPFS file Qmee2TBnTjYvLaLd4doyPc3q8xFtta3kPmiPsrbiUr4qSU is too large. It can be at most 1000000 bytes but is 1832859 bytes
error Command failed with exit code 1.
```

**Comment by leoyvens** [comment]
@wighawag Oh that's the Graph Node limit. It will be increased the next time we make an update to the hosted service.

**Comment by wighawag** [comment]
I guess the limit is there to avoid abuse of the API. It is not a limitation of graph-node, right ?
I am asking because I expect that number to grow a lot more for my use case.

If so could the graph-cli allow us to provide the ipfs hash and let us upload the ipfs hash by ourselves ?

**Comment by leoyvens** [comment]
@wighawag This is a configurable limit in Graph Node itself to prevent it from trying to process excessively large files. I've increased it to 10 MB per file, will that be enough for you?

**Comment by wighawag** [comment]
Thanks @leoyvens that would be enough for now, but I am also interested about the options long term
My use case require lots of data for the subgraph to be initialised and would like to know your plan in that regard to see if it will be a viable option as the data keep increasing.

**Comment by leoyvens** [comment]
@wighawag long term it will depend on what indexers in the network consider as a reasonable limit for this.

**Comment by wighawag** [comment]
Thanks @leoyvens for the calrification.
But should this not be per subgraph. I mean if a particular indexer choose to index one subgraph (because it was curated) and this subgraph happen to have lots of init data, why the limit should be there in grph-node. It is up to them to index that subgraph or not.

**Comment by leoyvens** [comment]
@wighawag The default is very large, we were using a much more conservative value on the hosted service. If this turns out to be an issue in practice we can consider a per subgraph limit.
