### ISSUE TITLE
npm install -g @graphprotocol/graph-cli fails with git@github.com: Permission denied (publickey)

### ISSUE THREAD

**Issue by shashi278** [graphprotocol/graph-cli#633]
I'm new to the graph and was just trying to follow from [the quick start](https://thegraph.com/docs/quick-start#3.-initialize-a-new-subgraph) but running `sudo npm install -g @graphprotocol/graph-cli` is failing with the below errors:
```bash
$ sudo npm install -g @graphprotocol/graph-cli
npm ERR! code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/hugomrdias/concat-stream.git
npm ERR! /bin/bash: /root/.bashrc: Permission denied
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-24T07_51_10_586Z-debug.log
```
`node -v`: v12.21.0
`npm -v`: 7.6.0
`OS`: Ubuntu 20.04.2 LTS

Relevant log bits:
```bash
1763 verbose stack Error: command failed
1763 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
1763 verbose stack     at ChildProcess.emit (events.js:314:20)
1763 verbose stack     at maybeClose (internal/child_process.js:1022:16)
1763 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
1764 verbose cwd /home/watney/Documents/graphtry/graph-node/docker
1765 verbose Linux 5.4.0-67-generic
1766 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "install" "-g" "@graphprotocol/graph-cli"
1767 verbose node v12.21.0
1768 verbose npm  v7.6.0
1769 error code 128
1770 error command failed
1771 error command git ls-remote ssh://git@github.com/hugomrdias/concat-stream.git
1772 error /bin/bash: /root/.bashrc: Permission denied
1772 error git@github.com: Permission denied (publickey).
1772 error fatal: Could not read from remote repository.
1772 error
1772 error Please make sure you have the correct access rights
1772 error and the repository exists.
1773 verbose exit 128
```
Any help is appreciated

**Comment by ArunSankarKs** [comment]
were you able to fix this. I am running into this same issue

**Comment by z3r0d0n3** [comment]
same issue, after adding my pub key to the git i'm getting a similar new one

npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects clone -b feat/smaller ssh://git@github.com/hugomrdias/concat-stream.git /root/.npm/_cacache/tmp/git-cloneygDekp --recurse-submodules --depth=1
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-cloneygDekp': Permission denied

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-09T14_00_39_830Z-debug.log

**Comment by plumflowa** [comment]
> 

Did you find a solutiion to this issue? I have sth similar

**Comment by ethanalef** [comment]
try yarn

**Comment by anxiaochuang** [comment]
I have also met, may I ask how to solve this problem?

**Comment by OleanjiKingCode** [comment]
Fixed the issue just had to upgrade to the latest version

**Comment by akshata112** [comment]
> Fixed the issue just had to upgrade to the latest version

Can you help me to solve the issue?
should I go for latest version of node?

**Comment by OleanjiKingCode** [comment]
@akshata112 I meant the latest version of graphprotocol...it kept installing a lower version until I checked the latest one and then installed while putting the version

**Comment by achal-singh** [comment]
I'd like to provide an additional example where I encountered the exact issue mentioned above. I received this error while executing **`npm install`** in this repository: https://github.com/georgeroman/erc20-subgraph.
Despite trying all the suggested solutions, what ultimately resolved the issue for me was removing the **`package-lock.json`** file and then running **`npm install`** again.

**Comment by dang1412** [comment]
Update this to the latest version solved the problem for me
```
"dependencies": {
    "@graphprotocol/graph-cli": "0.89.0",
    "@graphprotocol/graph-ts": "0.32.0"
  },
```
