### ISSUE TITLE
Multiple contracts support 

### ISSUE THREAD

**Issue by Moehringen** [graphprotocol/graph-cli#644]
Hi all, 

I have read the docs regarding multiple contracts(not too details in the docs). 
I am trying to get some data from a series contracts and these contracs are almost same(with minor differences) . 

my question is , is it possible to put several contracts in one subgragh  and how can I do it? e.g.:  in subgragh.yaml ,  put several contracs and with coresponding abi? 

thanks

**Comment by azf20** [comment]
Different contracts can be added as separate data sources in `subgraph.yaml` e.g. search "multiple smart contracts" here: https://thegraph.com/docs/define-a-subgraph#the-subgraph-manifest
