### ISSUE TITLE
Deployed HTML page is missing dependencies

### ISSUE THREAD

**Issue by TravelingTechGuy** [graphprotocol/graph-cli#661]
I've used the CLI to deploy a graph. The page I'm redirected to is perpetually showing "Loading.." so I dug in and found that 2 dependencies are returning 404:

1. https://api.thegraph.com/graphiql.css
2. https://api.thegraph.com/graphiql.min.js

This, of course explains why the page never renders. I'm assuming this is a bug in the HTML rendering process.
Can this be fixed? Where can i find these resources, so I can use the HTML page until a fix is issued?

I'm using v 0.20.0 of the CLI, with Node 16.1.0. Would gladly provide any other details required to solve.

PS:

I'm guessing the correct addresses are:

```html
<link rel="stylesheet" href="//unpkg.com/graphiql/graphiql.min.css" />
<script src="//unpkg.com/graphiql/graphiql.min.js"></script>
```

**Comment by schmidsi** [comment]
Thanks for pointing this out. Although your investigation is right, we do not intend to expose the standalone graphiql for each subgraph. The URL that you try to load is the actual GraphQL query endpoint that you should point your client to. The playground for your subgraphs is in the Graph Explorer.

For example: 
You can play around with the ENS subgraph explorer here: https://thegraph.com/explorer/subgraph/ensdomains/ens
And on the same page you see the URL to the query endpoint: https://api.thegraph.com/subgraphs/name/ensdomains/ens

Using your browser to view the query endpoint gives you a white screen. But if you use a GraphQL client like https://altair.sirmuel.design, you can inspect and interact with it.
