### ISSUE TITLE
unable to install graph-cli

### ISSUE THREAD

**Issue by Wakuangdachengzi** [graphprotocol/graph-cli#670]
Attempting to run npm install -g @graphprotocol/graph-cli in Ubuntu 18.04  command prompt results in the following output。
![RZ48 )2PY7W OB%B %SENXA](https://user-images.githubusercontent.com/80933753/120144629-d5fa0980-c214-11eb-89d2-82277b42f1eb.png)

**Comment by schmidsi** [comment]
Which node/npm version do you use?

**Comment by Wakuangdachengzi** [comment]
12.0.0

**Comment by schmidsi** [comment]
Can you just try again? Looking at the error message it seems like there was simply a temporary connection issue with Github. Feel free to reopen if the problem still exists.
