### ISSUE TITLE
Bug when build

### ISSUE THREAD

**Issue by trunks1031** [graphprotocol/graph-cli#671]
Hello guys, i just build a source then deploy but i got an error when run "yarn build:
Failed to compile subgraph: Failed to compile data source mapping: Import file 'src/types/Factory/Factory.ts' not found
Error: Failed to compile data source mapping: Import file 'src/types/Factory/Factory.ts' not found.
Can you help me ?

**Comment by schmidsi** [comment]
It seems like you forgot to run `yarn codegen` first. Otherwise, can you please point me to your repo, so I can have a look?

**Comment by schmidsi** [comment]
Closing this since I'm pretty sure the solution is simply to run `yarn codegen` first. Feel free to reopen if this did not solve your problem by providing more info to reproduce the error.
