### ISSUE TITLE
Error deploying a legacy subgraph

### ISSUE THREAD

**Issue by oikos1** [graphprotocol/graph-cli#711]
Hello,

Upon attempting to deploy a legacy subgraph using my access token, I get the following error:
`✖ Failed to deploy to Graph node https://api.thegraph.com/deploy/: Invalid account name or access token`

Commands used:
`graph auth --product hosted-service <MY_ACCESS_TOKEN_HERE>`

`graph deploy --product hosted-service oikos1/exchanger --ipfs https://api.thegraph.com/ipfs/ --node https://api.thegraph.com/deploy/ --debug`

The commands used were working before. Any idea what is causing the issue? 
Thanks in advance

**Comment by azf20** [comment]
Interesting thanks for reporting @oikos1  - does it work if you pass `--access-token <TOKEN_HERE>` when deploying?

**Comment by oikos1** [comment]
> Interesting thanks for reporting @oikos1 - does it work if you pass `--access-token <TOKEN_HERE>` when deploying?

My pleasure. Yes, it works by passing the parameter directly with -access-token, thank you!

**Comment by syuukawa** [comment]
did you fix this problem?

**Comment by oikos1** [comment]
> did you fix this problem?

It worked for me with the --access-token flag. Not sure if the bug is fixed though. Closing this as you guys are aware of the issue and a solution was provided. Thank you!
