### ISSUE TITLE
Invalid Ethereum network name [Arbitrum Testnet (on Rinkeby)]

### ISSUE THREAD

**Issue by syuukawa** [graphprotocol/graph-cli#716]
Just want to use Graph in Arbitrum Testnet , How to set the network in the subgraph.yaml

subgraph.yaml
    network: Arbitrum Testnet (on Rinkeby)

✖ Failed to deploy to Graph node https://api.thegraph.com/deploy/: Invalid manifest: Invalid Ethereum network name

**Comment by schmidsi** [comment]
Try setting:

```network: arbitrum-rinkeby```

I hope that helps. If not, please feel free to reopen this issue.

**Comment by syuukawa** [comment]
> Try setting:
> 
> `network: arbitrum-rinkeby`
> 
> I hope that helps. If not, please feel free to reopen this issue.

Tred network: arbitrum-rinkeby
