### ISSUE TITLE
How to get test GRT on Rinkeby

### ISSUE THREAD

**Issue by Clay9910** [graphprotocol/graph-cli#726]
How to get test GRT on Rinkeby?

Someone can send me some? thank you.

my address:0xDeE1EccC2E46E636E89F4996aC278815C2bc9295

**Comment by schmidsi** [comment]
[Since you were able to get some, I close this](https://rinkeby.etherscan.io/token/0x54fe55d5d255b8460fb3bc52d5d676f9ae5697cd?a=0xDeE1EccC2E46E636E89F4996aC278815C2bc9295).
