### ISSUE TITLE
Non Ethereum mainnet subgraphs should not be deployed to the studio

### ISSUE THREAD

**Issue by Loverush** [graphprotocol/graph-cli#748]
When I trid to deploy my subgraph studio on my test conctract(which was deployed on Kovan and Ropsten), I got **Non Ethereum mainnet subgraphs should not be deployed to the studio** on the final step `graph deploy --studio <SUBGRAPH_NAME>
`
<img width="498" alt="图片" src="https://user-images.githubusercontent.com/48975233/134131622-5777aec3-6286-47f8-9b49-14682fd59a54.png">

**Comment by Loverush** [comment]
I figured that this issue only happened with graph-cli 0.22.0.
Downgrade to 0.21.0 and it worked.

**Comment by schmidsi** [comment]
This is intended behaviour. The studio and decentralised network only support Ethereum mainnet at the moment. If you want to deploy to another chain, please use the legacy explorer: https://thegraph.com/legacy-explorer/

Feel free to reopen this issue if you think your question is not answered.
