### ISSUE TITLE
graph command not found after installing it with nmp on ubuntu

### ISSUE THREAD

**Issue by PabloTurnes** [graphprotocol/graph-cli#753]
I've tried to execute graph commands in a couple of ubuntu mahines after installing it but it doesn't seem to work, the version that I've installed is: @graphprotocol/graph-cli": "^0.22.2, I've also tried to install it with yarn but the result is the same

**Comment by otaviopace** [comment]
Hello Pablo, can you give more information so we can help you?

1. What error are you facing exactly?
2. Do you have any logs/text output?
3. Which commands failed?
4. Did you install the `graph-cli` globally or locally in a subgraph?
5. Are you sure the commands are running in the global/local `graph-cli`?

**Comment by fdmmarshall** [comment]
I had a similar issue, did you install the graph-cli using yarn? If so, try installing it with npm instead then run the command again.  I'm using ubuntu 20.04 on WSL 2.

**Comment by PabloTurnes** [comment]
I think that I'd tried npm and yarn, I ended up using docker and it worked well

**Comment by ayenisholah** [comment]
@PabloTurnes  how did you install the cli inside a docker container

**Comment by PabloTurnes** [comment]
@ayenisholah here is the Dockerfile that I've used:

`FROM debian
RUN apt update
RUN apt install nodejs -y 
RUN apt install npm -y
RUN apt install nano -y
RUN apt-get install libsecret-1-dev -y
RUN npm install npm@latest -g
RUN npm install -g @graphprotocol/graph-cli
RUN git config --global user.name "Your name"
RUN git config --global user.email "youremail@yourdomain.com"`

**Comment by ayenisholah** [comment]
Thank you.
