### ISSUE TITLE
fucking error macos cata and ubuntu please help

### ISSUE THREAD

**Issue by v3rangar** [graphprotocol/graph-cli#774]
graph deploy --studio guguli
✔ Version Label (e.g. v0.0.1) · 0.1
  Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2
  Skip migration: Bump mapping apiVersion from 0.0.2 to 0.0.3
  Skip migration: Bump mapping apiVersion from 0.0.3 to 0.0.4
  Skip migration: Bump mapping apiVersion from 0.0.4 to 0.0.5
  Skip migration: Bump mapping specVersion from 0.0.1 to 0.0.2
✔ Apply migrations
✔ Load subgraph from subgraph.yaml
  Compile data source: Token => build/Token/Token.wasm
⠋ Compile subgraphERROR TS2305: Module 'generated/schema' has no exported member 'Token'.

   Token, User
   ~~~~~
 in src/mapping.ts(9,3)

ERROR TS2305: Module 'generated/schema' has no exported member 'User'.

   Token, User
          ~~~~
 in src/mapping.ts(9,10)

ERROR TS2304: Cannot find name 'Token'.

   let token = Token.load(event.params.tokenId.toString());
               ~~~~~
 in src/mapping.ts(13,15)

ERROR TS2304: Cannot find name 'Token'.

     token = new Token(event.params.tokenId.toString());
                 ~~~~~
 in src/mapping.ts(15,17)

ERROR TS2339: Property 'creator' does not exist on type 'i32'.

     token.creator = event.params.to.toHexString();
           ~~~~~~~
 in src/mapping.ts(16,11)

ERROR TS2339: Property 'tokenID' does not exist on type 'i32'.

     token.tokenID = event.params.tokenId;
           ~~~~~~~
 in src/mapping.ts(17,11)

ERROR TS2339: Property 'createdAtTimestamp' does not exist on type 'i32'.

     token.createdAtTimestamp = event.block.timestamp;
           ~~~~~~~~~~~~~~~~~~
 in src/mapping.ts(18,11)

ERROR TS2339: Property 'contentURI' does not exist on type 'i32'.

     token.contentURI = tokenContract.tokenURI(event.params.tokenId);
           ~~~~~~~~~~
 in src/mapping.ts(21,11)

ERROR TS2339: Property 'metadataURI' does not exist on type 'i32'.

     token.metadataURI = tokenContract.tokenMetadataURI(event.params.tokenId);
           ~~~~~~~~~~~
 in src/mapping.ts(22,11)

ERROR TS2339: Property 'owner' does not exist on type 'i32'.

   token.owner = event.params.to.toHexString();
         ~~~~~
 in src/mapping.ts(24,9)

ERROR TS2339: Property 'save' does not exist on type 'i32'.

   token.save();
         ~~~~
 in src/mapping.ts(25,9)

ERROR TS2304: Cannot find name 'User'.

   let user = User.load(event.params.to.toHexString());
              ~~~~
 in src/mapping.ts(27,14)

ERROR TS2304: Cannot find name 'User'.

     user = new User(event.params.to.toHexString());
                ~~~~
 in src/mapping.ts(29,16)

ERROR TS2339: Property 'save' does not exist on type 'i32'.

     user.save();
          ~~~~
 in src/mapping.ts(30,10)

ERROR TS2304: Cannot find name 'Token'.

   let token = Token.load(event.params._tokenId.toString());
               ~~~~~
 in src/mapping.ts(35,15)

ERROR TS2339: Property 'contentURI' does not exist on type 'i32'.

   token.contentURI = event.params._uri;
         ~~~~~~~~~~
 in src/mapping.ts(37,9)

ERROR TS2339: Property 'save' does not exist on type 'i32'.

   token.save();
         ~~~~
 in src/mapping.ts(38,9)

ERROR TS2304: Cannot find name 'Token'.

    let token = Token.load(event.params._tokenId.toString());
                ~~~~~
 in src/mapping.ts(42,16)

ERROR TS2339: Property 'metadataURI' does not exist on type 'i32'.

    token.metadataURI = event.params._uri;
          ~~~~~~~~~~~
 in src/mapping.ts(44,10)

ERROR TS2339: Property 'save' does not exist on type 'i32'.

    token.save();
          ~~~~
 in src/mapping.ts(45,10)

✖ Failed to compile subgraph: Failed to compile data source mapping: 20 compile error(s)
Error: Failed to compile data source mapping: 20 compile error(s)
    at Compiler._compileDataSourceMapping (/usr/local/lib/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:307:13)
    at /usr/local/lib/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:216:20
    at updateInDeepMap (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:1971:22)
    at updateInDeepMap (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:1980:23)
    at updateInDeepMap (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:1980:23)
    at Map.updateIn (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:1278:26)
    at /usr/local/lib/node_modules/@graphprotocol/graph-cli/src/compiler/index.js:215:24
    at /usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:3016:46
    at List.__iterate (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:2206:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/usr/local/lib/node_modules/@graphprotocol/graph-cli/node_modules/immutable/dist/immutable.js:3015:23)
UNCAUGHT EXCEPTION: Error: The AssemblyScript compiler crashed when compiling this file: 'src/mapping.ts'
Suggestion: try to comment the whole file and uncomment it little by little while re-running the graph-cli until you isolate the line where the problem happens.
Also, please contact us so we can make the CLI better by handling errors like this. You can reach out in any of these links:
- Discord channel: https://discord.gg/eM8CA6WA9r
- Github issues: https://github.com/graphprotocol/graph-cli/issues

**Comment by otaviopace** [comment]
Hello @v3rangar it seems that your `.graphql` file doesn't have the types you're expecting in the mapping ones. After you add them (such as `User`) make sure you to run ` graph codegen` again :slightly_smiling_face:

**Comment by v3rangar** [comment]
> Hello @v3rangar it seems that your `.graphql` file doesn't have the types you're expecting in the mapping ones. After you add them (such as `User`) make sure you to run ` graph codegen` again 🙂

hi brother thanks to reply
after re codegen
 Version Label (e.g. v0.0.1) · v0.0.1
  Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2
  Skip migration: Bump mapping apiVersion from 0.0.2 to 0.0.3
  Skip migration: Bump mapping apiVersion from 0.0.3 to 0.0.4
  Skip migration: Bump mapping apiVersion from 0.0.4 to 0.0.5
  Skip migration: Bump mapping specVersion from 0.0.1 to 0.0.2
✔ Apply migrations
✔ Load subgraph from subgraph.yaml
  Compile data source: Token => build/Token/Token.wasm
✔ Compile subgraph
  Copy schema file build/schema.graphql
  Write subgraph file build/Token/abis/Token.json
  Write subgraph manifest build/subgraph.yaml
✔ Write compiled subgraph to build/
  Add file to IPFS build/schema.graphql
                .. QmRdU9R5Peg9zeDaose3uMmDqnzDc2sYdNUisz3dUXE1Su
  Add file to IPFS build/Token/abis/Token.json
                .. QmRHhpdZ6RKT573ko2oC976V7WyZ86xkqV4xgeUVDx5heb
  Add file to IPFS build/Token/Token.wasm
                .. QmSvyrxMmhaXkUWz8GK874Hpv6m9deUfyq3ENTnhsc9b4v
✔ Upload subgraph to IPFS

Build completed: Qma3Qgg1zQYDfFXxqNnccmTQZhKt2iuz9dX9ZFDRwvpejd

✖ Failed to deploy to Graph node https://api.studio.thegraph.com/deploy/: Subgraph not found.


everything is fine but this error   ✖ Failed to deploy to Graph node https://api.studio.thegraph.com/deploy/: Subgraph not found.

how to solve it???

**Comment by otaviopace** [comment]
Before running `graph deploy` you must run `graph create` to register the subgraph name.

**Comment by v3rangar** [comment]
thanks bro it is solved @otaviopace
