### ISSUE TITLE
Watch Mode

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-cli#79]
Right now, after each change to a mapping, the developer has to complete the following steps: 
- Generate types to write your mappings
- Compile your subgraph and mappings
- Deploy your subgraph manifest to IPFS
- Deploy your subgraph to Graph Node
It would be much better if this could all be done in a single step during development and if that command could be executed on save.

**Comment by fordN** [comment]
Auto deploying subgraph to the Graph Node dependent on #227 and #168
