### ISSUE TITLE
Support `arbitrum-one` through graph-init

### ISSUE THREAD

**Issue by schmidsi** [graphprotocol/graph-cli#792]
Add it here:
https://github.com/graphprotocol/graph-cli/blob/master/src/commands/init.js#L279-L287

The correct URL is: https://api.arbiscan.io/api 

https://arbiscan.io/address/0x1b02da8cb0d097eb8d57a175b88c7d8b47997506

**Comment by 0xkarel** [comment]
@schmidsi just to add - should be added `https://api.arbiscan.io/api` to the list instead as the API URL.

**Comment by schmidsi** [comment]
@0xkarel, correct. I was too quick copy/pasting. Updated the description.

**Comment by schmidsi** [comment]
@0xkarel Feel free to open a pull-request ;)
