### ISSUE TITLE
Compiling error trying to convert Address[] to [Bytes!]!

### ISSUE THREAD

**Issue by tapmapp** [graphprotocol/graph-cli#817]
Hello,
I am having a compiling error on my handler trying to convert **Address[] to [Bytes!]!**
Please, i need urgent help! 
Thank you in advance

My graphql schema:

type WhitelistAddressesEvent @entity {
  id: ID!
  token: Bytes! # address
  protectedAddress: Bytes! # address
  **whitelist: [Bytes!]!**
  state: Boolean!
}

My handler:

export function handleWhitelistAddresses(event: WhitelistAddresses): void {
  let entity = WhitelistAddressesEvent.load(event.transaction.from.toHex());
  if (!entity) {
    entity = new WhitelistAddressesEvent(event.transaction.from.toHex());
  }
 
  **entity.whitelist = event.params.whitelist;**

  entity.save();
}

My WhitelistAddresses__Params class:

export class WhitelistAddresses__Params {
  _event: WhitelistAddresses;

  constructor(event: WhitelistAddresses) {
    this._event = event;
  }

  **get whitelist(): Array<Address> {
    return this._event.parameters[2].value.toAddressArray();
  }**

}

**Comment by tapmapp** [comment]
Hi all,

I found a way.

  **entity.whitelist = Value.fromAddressArray(
    event.params.whitelist
  ).toBytesArray();**

}

**Comment by azf20** [comment]
Hi @tapmapp - glad you got it sorted, thanks for sharing your solution, will close this issue, please do re-open if your issue is not yet solved
