### ISSUE TITLE
`graph test` args not forwarded to matchstick

### ISSUE THREAD

**Issue by gbarros** [graphprotocol/graph-cli#829]
Recently, I've changed the project I am working on to a monorepo using yarn workspaces and `graph test` cmd stopped working. 

Investigating a little I've found out that `matchstick` binary needs the path for the `node_modules` of the monorepo and not the package. Using the binary directly I could then correct this issue by adding `--lib ../path/to/node_modules`.

However, I can't really work around the fact that the graph-cli doesn't forward any args to matchstick that is not already mapped. So maybe we could add this `--lib` one to the options available.

**Comment by dimitrovmaksim** [comment]
Sorry for the late reply, you can now use [matchstick.yaml](https://github.com/LimeChain/matchstick#configuration-%EF%B8%8F) config to declare custom libsFolder or testsFolder

**Comment by azf20** [comment]
Thanks @dimitrovmaksim and @gbarros ! Closing this as I think that resolves the issue, but @gbarros please do re-open if you are still having trouble
