### ISSUE TITLE
graph deploy failed after following the steps of Donumentation

### ISSUE THREAD

**Issue by ZhaojiaLii** [graphprotocol/graph-cli#841]
Hi, I've met a wired failure when I run <graph deploy --studio test> from local.
I've followed the steps from the official website:
======== INIT ========
1. graph init --studio test

==== AUTH & DEPLOY ====

2. graph auth  --studio 8805c0—150933
3. cd test
4. graph codegen && graph build
these 4 steps above were all done successfully, but I got the error below when I running the 5th step <graph deploy --studio test>:
**Deploying to Graph node https://api.studio.thegraph.com/deploy/UNCAUGHT EXCEPTION: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Authorization"]**
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/34066205/155323681-4d69653d-df79-4ae3-a775-c7e6670f8ecc.png">

pkg version:
@graphprotocol/graph-cli^0.26.0

I've tried several times but nothing changed, plz help ~

**Comment by ZhaojiaLii** [comment]
I don't know if it's problem of the authorization step or not..

**Comment by sherodtaylor** [comment]
I've been getting the same issue ^ 

```

✔ Upload subgraph to IPFS

Build completed: QmRPSwtZHy3FESEVo6sy3FTAF9q1ybcVKhp4yBXiuG8uqh

⠋ Deploying to Graph node https://api.studio.thegraph.com/deploy/UNCAUGHT EXCEPTION: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Authorization"]
⠋ Deploying to Graph node https://api.studio.thegraph.com/deploy/

```

**Comment by azf20** [comment]
hi @ZhaojiaLii and @sherodtaylor I think you are not putting the correct authorization token. Did you use the `copy` button to get the auth token? the deploy key shown is just the start and the end  of the token, you need to press copy to get the whole thing
<img width="247" alt="image" src="https://user-images.githubusercontent.com/9612972/157440812-0222c3b0-3eae-4757-abed-9101920b944d.png">

**Comment by sherodtaylor** [comment]
yeah i fixed that @azf20 thats a pretty frustrating ux experience because it looks like a valid key with `-`. I would change the UI dash to `...` and make the section selectable.

**Comment by keon** [comment]
yeah `...` would make more sense

**Comment by raparri01** [comment]
> yeah i fixed that @azf20 thats a pretty frustrating ux experience because it looks like a valid key with `-`. I would change the UI dash to `...` and make the section selectable.

The fact that the same behavior is present in the "Auth & Deploy" steps makes this issue even worse. 

![image](https://user-images.githubusercontent.com/32496022/162041411-0acd9899-260a-47d7-b8b8-cf2555935642.png)

**Comment by ZhaojiaLii** [comment]
ok I solved the problem by copy the right key, the key with " - " is absolutely awesome lol, anyway thank all ~
have a nice weekend !
