### ISSUE TITLE
Unexpected key in map: features

### ISSUE THREAD

**Issue by Addy0119** [graphprotocol/graph-cli#858]
![image](https://user-images.githubusercontent.com/58567154/159629859-98075e7f-b157-46c8-ad64-fd85184e0577.png)

Here is subgraph.yaml file:
![image](https://user-images.githubusercontent.com/58567154/159630100-f3884e8a-1b9c-4d4e-9847-c77eba025cd6.png)

Node package:

![image](https://user-images.githubusercontent.com/58567154/159630156-39c6ae87-dfb4-4404-8a80-8c03884549ad.png)

**Comment by dimitrovmaksim** [comment]
It seems `features` is supported only for ethereum contracts

**Comment by azf20** [comment]
> It seems `features` is supported only for ethereum contracts

@tilacog is this the case?

**Comment by tilacog** [comment]
It should work to work for all supported networks, not only Ethereum.

@Addy0119, I noticed you invoked the `graph` command directly. Could you please confirm that your `graph` command is at the same version as the one in your `package.json`?

You could do that by comparing the output of these two commands:
```
$ graph --version
$ yarn graph --version
```

**Comment by dimitrovmaksim** [comment]
https://github.com/graphprotocol/graph-cli/blob/main/src/protocols/ethereum/manifest.graphql#L14 this field is missing from the other protocols' `manifest.graph`

**Comment by tilacog** [comment]
@dimitrovmaksim you are correct, thanks for the clarification.
For one moment I misunderstood "Ethereum" for "Ethereum Mainnet", I apologize.

**Comment by tilacog** [comment]
While the fix for this issue is straightforward, we might want to discuss a less confusing name for the `ipfsOnEthereumContracts` feature.

Maybe we could create an alias for it to be used in non-evm chains.
