### ISSUE TITLE
^0.27.0 break while generating complex types

### ISSUE THREAD

**Issue by jjranalli** [graphprotocol/graph-cli#862]
I have an event that emits an array of structs, and codegen breaks with the following error (using latest `graph-cli 0.29.0` and `graph-ts 0.26.0`)

`Failed to generate types for contract ABIs: Failed to generate types for contract ABI: Conversion from 'AssemblyScript' to 'ethereum' for source type 'Array<TokenSlicedPayeesStruct>' is not supported`

Downgrading graph-cli to 0.26.0 solves the issue, so I assume the issue was introduced in 0.27.0

**Comment by evaporei** [comment]
I think I know where this comes from, I'll take a look this Friday, sorry for the long wait!

**Comment by poria-cat** [comment]
I was sure there would be such a problem, because of this I had to change the structure of the contract lol

**Comment by evaporei** [comment]
I'm coming back to this issue, I'm sorry I was OOO (out of office). 👩‍💻

**Comment by schmidsi** [comment]
@evaporei Reproduced in this branch:

https://github.com/schmidsi/nxtp/tree/conversion-bug

Steps to reproduce:
- Clone
- `yarn`
- `cd packages/subgraph`
- `yarn prepare:local`
- `yarn codegen` -> This should break

**Comment by evaporei** [comment]
@schmidsi thanks for the example

I just found the bug, I'll submit a few patches for the affected versions soon 🙂

**Comment by evaporei** [comment]
It's patched on: 

- https://github.com/graphprotocol/graph-cli/releases/tag/v0.27.1
- https://github.com/graphprotocol/graph-cli/releases/tag/v0.28.3
- https://github.com/graphprotocol/graph-cli/releases/tag/v0.29.2
