### ISSUE TITLE
Error in Graph CLI installation on Ubuntu

### ISSUE THREAD

**Issue by ameya-deshmukh** [graphprotocol/graph-cli#876]
I've been having issues with installing The Graph CLI on my Ubuntu system (Ubuntu 21.10) from the terminal:

The commands and issues I've been facing with npm and yarn respectively are 
# npm 
` ` `
npm install -g @graphprotocol/graph-cli
` ` `
` ` `
npm ERR! code 128
` ` `
` ` `
npm ERR! An unknown git error occurred
` ` `
` ` `
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/edgeandnode/gluegun.git
` ` `
` ` `
npm ERR! git@github.com: Permission denied (publickey).
` ` `
` ` `
npm ERR! fatal: Could not read from remote repository.
` ` `
` ` `
npm ERR!
` ` `
` ` `
npm ERR! Please make sure you have the correct access rights
` ` `
` ` `
npm ERR! and the repository exists.
` ` `
` ` `
npm ERR! A complete log of this run can be found in:
` ` `
` ` `
npm ERR!     /root/.npm/_logs/2022-04-17T16_15_12_965Z-debug-0.log
` ` `

# Yarn
` ` `yarn global add @graphprotocol/graph-cli
` ` `
No errors while installation, but when I run the command 'graph' on the terminal, it does not show up

**Comment by incrypto32** [comment]
@ameya-deshmukh On Ubuntu, you can try `sudo npm install -g @graphprotocol/graph-cli` On linux to install global packages you need root privileges.

If you are using yarn it installs the package to a directory within your home directory but you will need to manually add the yarn bin directory to the `$PATH`. You can check this [answer](https://stackoverflow.com/a/53879534) to do that.

I'm closing the issue. Feel free to comment here and tag me if you face any difficulties

**Comment by ameya-deshmukh** [comment]
Thank you. Yes I did try ` ` `sudo npm install -g @graphprotocol/graph-cli` ` ` but apparently that's giving the same results. WIll check out the yarn method though. Thanks.

**Comment by ameya-deshmukh** [comment]
> @ameya-deshmukh On Ubuntu, you can try `sudo npm install -g @graphprotocol/graph-cli` On linux to install global packages you need root privileges.
> 
> If you are using yarn it installs the package to a directory within your home directory but you will need to manually add the yarn bin directory to the `$PATH`. You can check this [answer](https://stackoverflow.com/a/53879534) to do that.
> 
> I'm closing the issue. Feel free to comment here and tag me if you face any difficulties

Yup, the yarn solution worked just fine! Thanks a lot. I know that this isn't part of the core issue, but any resources to help me get the npm part fixed?

**Comment by incrypto32** [comment]
@ameya-deshmukh on second thought the issue with npm is most likely an outdated npm version error rather than a  root permission issue. can you try updating npm using `npm install npm@latest -g` and rerunning the install
