### ISSUE TITLE
Namespace or de-duplicate conflicting ABI types

### ISSUE THREAD

**Issue by leodasvacas** [graphprotocol/graph-cli#88]
Livepeer reported that their contracts `BondingManager` and `RoundsManager` share some types, causing a name conflict when the ABIs of both contracts are added to a same mapping. The best solution would be to namespace the types by contract, but in this case since the types are equal de-duplicating would suffice.

**Comment by Jannis** [comment]
Prefixing would generate long, not very user-friendly type names. I wonder if we could make it so that users can import the types they want selectively, e.g. with

```typescript
import type { SomeType } from 'path/to/Contract.types.ts'
```

Need to think about this a bit more.

**Comment by Jannis** [comment]
This is now possible, so we can close the issue.
