### ISSUE TITLE
The subgraph violates data normalization (1NF) ?

### ISSUE THREAD

**Issue by wdYangX** [graphprotocol/graph-cli#910]
Hi ! I am a blockchain developer. When I use subgraph to expect, I record the data block chain to the databasse and use the query in the databse. But I am interested in the records to the database. When I design the schema, I expect every record to be Add, Update, Edit. If it already exists then the record won't be updated. But graph mechanics won't create 1 record into the database. This would violate data normalization (1NF).
In the db:
<img width="626" alt="Screen Shot 2022-06-17 at 18 24 04" src="https://user-images.githubusercontent.com/81003112/174289253-1977c221-1bed-4d7a-973a-d8384e0e9415.png">
In the graph:
<img width="1361" alt="Screen Shot 2022-06-17 at 18 17 14" src="https://user-images.githubusercontent.com/81003112/174289362-2e81afba-8b63-4db2-b5df-babf34f94ad4.png">
Schema:

type CardEntity @entity @key(fields: "id"){
    id: ID!
    tokenId: BigInt!
    owner: Bytes!
    createAt: BigInt!
    updateAt: BigInt!
}
# Define schema
    let entity = CardEntity.load(event.params.tokenId.toString())
    if (entity) {
        entity.owner = event.params.to
        entity.updateAt = event.block.timestamp
    }
    else {
        entity = new CardEntity(event.params.tokenId.toString())
        entity.tokenId = event.params.tokenId
        entity.owner = event.params.to
        entity.createAt = event.block.timestamp
        entity.updateAt = event.block.timestamp
    }
    entity.save()

**Comment by Jannis** [comment]
What is stored in the database are versions of entities as they were/are valid for specific block ranges on chain. This is important for handling chain reorgs as well as querying historic data.
