### ISSUE TITLE
Storing ABIs outside subgraph folder causes Cloudflare error when deploying subgraph. 

### ISSUE THREAD

**Issue by pranavdaa** [graphprotocol/graph-cli#925]
If we store the ABI outside the subgraph folder it shows cloudflare error -
`This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.`
This seems to be a limitation on the graph-cli end. Do resolve it

**Temporary solution**: Store the ABI inside the subgraph folder

**Comment by azf20** [comment]
This is a new error affecting previously functional `graph-cli` / subgraph combinations, so it suggests a change in Cloudflare cc @evaporei ?

**Comment by azf20** [comment]
This was resolved on the cloudflare side
