### ISSUE TITLE
graph test fails to fetch matchstick binary

### ISSUE THREAD

**Issue by jeffchenpv** [graphprotocol/graph-cli#928]
cli version: 0.32.0

graph test fetches `binary-macos-10.14` from matchstick 0.5.1 but it returns 404. Could the binary be updated?

Here is the error: ```Downloading release from https://github.com/LimeChain/matchstick/releases/download/0.5.1/binary-macos-10.14
Error fetching release: Request failed with status code 404```

**Comment by dimitrovmaksim** [comment]
GitHub removed support for 10.14 environments and 10.14 binaries can't be built anymore using github actions

**Comment by jeffchenpv** [comment]
Hi @dimitrovmaksim , I downloaded the binary and ran it in my project root, but it doesn't pick up any tests. Here is error I get `thread 'main' panicked at '🆘 No tests have been written yet.', src/compiler/sources.rs:20:13`.

**Comment by jeffchenpv** [comment]
Hi @dimitrovmaksim, thanks for the info. I was able to run it with 10.15 binary. Would graph cli get updated to use 10.15?

**Comment by dimitrovmaksim** [comment]
Yeah, we will update the graph-cli

**Comment by jeffchenpv** [comment]
Awesome, thanks for the update
