### ISSUE TITLE
Cannot Deploy Ropsten Subgraph

### ISSUE THREAD

**Issue by 0xrin1** [graphprotocol/graph-cli#956]
```
Failed to deploy to Graph node https://api.thegraph.com/deploy/: network not supported by registrar: no network ropsten found on chain ethereum
 ```

Is this something new because of the merge or do I have something configured incorrectly?
The same deployment with ropsten configured as the address used to work for me

**Comment by azf20** [comment]
Hi! Sorry about this. [Ropsten is being deprecated](https://blog.ethereum.org/2022/06/21/testnet-deprecation) and is no longer supported on the Hosted Service
