### ISSUE TITLE
Update network name: xdai -> gnosis

### ISSUE THREAD

**Issue by fordN** [graphprotocol/graph-cli#966]
As we migrate `network: xdai` subgraphs to now use `network: gnosis` we'll need to update graph-cli to use the new name.  

Mentions of `xdai` in codebase:
https://github.com/graphprotocol/graph-cli/blob/main/src/protocols/index.js#L49
https://github.com/graphprotocol/graph-cli/blob/main/src/validation/manifest.js#L250-L258
https://github.com/graphprotocol/graph-cli/blob/main/src/command-helpers/studio.test.js#L18
https://github.com/graphprotocol/graph-cli/blob/main/src/command-helpers/studio.test.js#L37

We may also need to update the Etherscan API unless it is auto-generated from the network name, so errors like the following don't crop up during `init`: 
```
✖ Failed to fetch ABI from Etherscan: request to https://api-xdai.etherscan.io/api?module=contract&action=getabi&address=0x5D48C95AdfFD4B40c1AAADc4e08fc44117E02179 failed, reason: getaddrinfo ENOTFOUND api-xdai.etherscan.io```

**Comment by azf20** [comment]
👍 - xdai (Gnosis) only recently got an Etherscan at https://gnosisscan.io/

**Comment by evaporei** [comment]
Done in `graph-cli@0.35.0`
