### ISSUE TITLE
Add xdai/gnosis to studio supported networks

### ISSUE THREAD

**Issue by cmwhited** [graphprotocol/graph-cli#967]
Studio needs to start supporting subgraph deployment to `xdai/gnosis`

Looks like support needs to be added [here](https://github.com/graphprotocol/graph-cli/blob/28a303a9a5162825fd435815fc8726dd7b88d053/src/command-helpers/studio.js#L1)

**Comment by azf20** [comment]
Hi! There is an open PR here for this https://github.com/graphprotocol/graph-cli/pull/960
@evaporei i think we are good to merge?

**Comment by cmwhited** [comment]
> Hi! There is an open PR here for this #960 @evaporei i think we are good to merge?

Oh awesome. I looked briefly but not close enough, obviously. Thanks @azf20
