### ISSUE TITLE
Generate classes for each entity type

### ISSUE THREAD

**Issue by yanivtal** [graphprotocol/graph-cli#97]
Rather than instantiating a generic Entity class and setting the fields individually like this
```
  let application = new Entity()
  application.setString('id', listingHash)
  application.setU256('expirationDate', listingResult.value0)
  application.setBoolean('whitelisted', listingResult.value1)
  application.setAddress('owner', listingResult.value2)
  application.setU256('deposit', listingResult.value3)
```
It would be better if we could instantiate an entity type specific class and set the data as a map like this
```
let application = new ApplicationEntity({
  id: listingHash,
  expirationDate: listingResult.value0,
  whitelisted: listingResult.value1,
  owner: listingResult.value2,
  deposit: listingResult.value3
})
```
Questions:
- How should we namespace these classes so they don't conflict?
- Should we change our current habit of injecting globals an instead make a module available so that people can manually import the classes they want at the top of the file?

**Comment by Jannis** [comment]
Summary for future development updates:
> Until now, subgraph mappings that read/wrote data from the store did so using a generic, low-level Entity class. Since we were already generating higher-level types for smart contracts and events, it made sense to also generate types for entity types defined in the subgraph's GraphQL schema. This provides type-safety for all GraphQL types and their fields. Instead of doing `let entity = new Entity(); entity.setString("attrName", ...)` you can now do `let token = new Token(); token.attrName = ...`.

**Comment by Jannis** [comment]
A maybe better summary for development updates:

> # Code generation for GraphQL schema types
> 
> The code generation we implemented for Ethereum smart contract ABIs enables developers to interact with contracts in their own language-contract names, function names, events names-as opposed to using the low-level EthereumEvent and SmartContract APIs.
>
> In time for ETHSanFrancisco, we are adding the same kind of code generation for entity types defined in the GraphQL schema. Instead of working with the lower-level Entity class directly, graph codegen now generates Entity subclasses for all types in the schema. Instead of
> ```
> let parcel = new Entity()
> parcel.setBigInt('x', someBigInt)
> parcel.setAddress('owner', event.sender)
> ```
> it is now possible to write
> ```
> import { Parcel } from './types/schema'
> let parcel = new Parcel()
> parcel.x = someBigInt
> parcel.address = event.sender
> ```
