### ISSUE TITLE
Multi-dimensional Arrays in v0.34 Error

### ISSUE THREAD

**Issue by illestrater** [graphprotocol/graph-cli#972]
Hi @evaporei looks like I'm running into an issue referencing: https://github.com/graphprotocol/graph-cli/issues/342

I'm successfully able to use codegen and write my handlers fine, but getting an error on build specifically on the multidimensional arrays. Typescript is showing the error for the generated schema as well.

```
ERROR TS2339: Property 'fromStringMatrix' does not exist on type '~lib/@graphprotocol/graph-ts/common/value/Value'.

     this.set("values", Value.fromStringMatrix(value));
                              ~~~~~~~~~~~~~~~~
 in generated/schema.ts(1300,30)

ERROR TS2339: Property 'fromBigIntMatrix' does not exist on type '~lib/@graphprotocol/graph-ts/common/value/Value'.

     this.set("valuesChance", Value.fromBigIntMatrix(value));
                                    ~~~~~~~~~~~~~~~~
 in generated/schema.ts(1318,36)
```

Here's the generated code snippet:

```
get values(): Array<Array<string>> {
    let value = this.get("values");
    return value!.toStringArray();
  }

  set values(value: Array<Array<string>>) {
    this.set("values", Value.fromStringMatrix(value));
  }

  get valuesChance(): Array<Array<BigInt>> {
    let value = this.get("valuesChance");
    return value!.toStringArray();
  }

  set valuesChance(value: Array<Array<BigInt>>) {
    this.set("valuesChance", Value.fromBigIntMatrix(value));
  }
```

Solidity model:

```
  struct CanvasTraits {
    string[] urlParams;
    string[] traits;
    string[][] values;
    uint16[] traitsChance;
    uint16[][] valuesChance;
  }
```

**Comment by azf20** [comment]
thanks @illestrater, what version of `graph-cli` and `graph-ts` are you using? @evaporei any thoughts on this

**Comment by boyuanx** [comment]
I'm having this issue as well, more specifically:

Definition in Solidity:
```
struct A {
   uint256[][] n
}
```

Error that I get when building:
```
ERROR TS2339: Property 'fromBigIntMatrix' does not exist on type '~lib/@graphprotocol/graph-ts/common/value/Value'.

         Value.fromBigIntMatrix(<Array<Array<BigInt>>>value)
               ~~~~~~~~~~~~~~~~
 in generated/schema.ts(310,15)
```

Versions: 
```
    "@graphprotocol/graph-cli": "0.35.0",
    "@graphprotocol/graph-ts": "0.28.1"
```

**Comment by azf20** [comment]
example repo https://github.com/boyuanx/Subgraph-Demo

here is the error: 
![image](https://user-images.githubusercontent.com/9612972/209095094-47bbde11-e059-4245-9639-71b08b0f9ddc.png)

**Comment by evaporei** [comment]
You can use `graph-ts` version `0.29.1`, that will fix the issue :wink:

**Comment by boyuanx** [comment]
Hi @evaporei , building now works but when I try to query a 2D array, it shows the following error:

"message": "Feature `nested list types` is not yet implemented"
